### ISSUE TITLE
Clarification about credentials

### ISSUE THREAD

**Issue by Kikobeats** [GoogleChrome/lighthouse-keeper#25]
Hello,

I tried to run the service locally; However I can't because

> You will be prompted to for a passphrase to decrypt serviceAccount.json.enc and memcacheCredentials.json.enc. These files are required for the backend to communicate with Firestore and the Redis memcache service. The password can be found in Google's shared password tool.

so I guess this project was an internal thing and now it's something public on the internet.

How to make possible run my own version of the service? What's the format the configuration file should be followed?

**Comment by robdodson** [comment]
You'd need to set up those services yourself using a GCP project and then download the required keys.

I don't think we're planning to offer widespread support on this project (as you mentioned, we mostly use it for internal stuff but did open source it). If you need to run your own monitoring service an easier route might be to use https://github.com/GoogleChrome/lighthouse-ci or use a paid service like https://speedcurve.com/ or https://calibreapp.com/

**Comment by paulirish** [comment]
@robdodson wanna tweak the repo description/readme with something like the paragraph you just wrote? :)

**Comment by paulirish** [comment]
Also, this repo should probably move to GoogleChromeLabs to help clarify that distinction.

**Comment by robdodson** [comment]
yep I've added a note to the top of the repo.

@jeffposnick are you able to transfer this repo to GoogleChromeLabs?

**Comment by jeffposnick** [comment]
Looks like I can, yeah. CC: @developit as a heads-up.

**Comment by Kikobeats** [comment]
is this project the thing running behind https://web.dev/measure?

It's very useful, not sure how lighthouse-ci is replacing it :(

**Comment by robdodson** [comment]
> is this project the thing running behind https://web.dev/measure?

Yep it's the server that we use to feed data to the dashboard you see on /measure.

> It's very useful, not sure how lighthouse-ci is replacing it :(

Essentially what this tool is doing is calling the pagespeed insights API (which is powered by Lighthouse) and storing the historical report data which we then fetch and visualize on web.dev/measure.

Lighthouse CI offers similar functionality with the ability [to upload your Lighthouse audits to a dashboard](https://github.com/GoogleChrome/lighthouse-ci#use-cases). Because Lighthouse CI provides GitHub Apps and Actions, my hunch is it may be easier to set up and use versus running lighthouse-keeper directly. For example, if you're running ligthhouse-keeper you'll have to build your own front-end to visualize the data, but [Lighthouse CI provides a server that will do this for you](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/server.md).

I may not be understanding your use case though so please let me know if I've missed something :)

**Comment by Kikobeats** [comment]
@robdodson Thanks for the reply, it clarifies me a lot and now I can see how powerful Lighthouse CI is 🙂

My use case is: I'm running [Microlink Insights](https://microlink.io/insights?url=https%3A%2F%2Fgithub.com) service that essentially generates Lighthouse report on demand, making you not worry about infrastructure stuff, just ping an API endpoint and you get the report back.

I discovered this repository cause I want to be sure I can connect the service with the rest of Lighthouse tools, so I guess I should be take a look into Lighthouse CI codebase to see how it really works
